project:
  type: website
  output-dir: docs

website:
  title: "CADERNO DE AULAS"
  navbar:
    background: "#87CEEB"
    primary: "#B0E0E6"
    left:
      - text: "Home"
        href: index.qmd

    right:
      - icon: github
        href: "https://github.com/igosarmento"
      - icon: search

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-after-body:
      - text: |
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
          <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Playfair+Display:wght@700&display=swap" rel="stylesheet">
